### ISSUE TITLE
sktime - collaborate?

### ISSUE THREAD

**Issue by fkiraly** [JoaquinAmatRodrigo/skforecast#223]
Hi, this looks pretty similar to `sktime`, specifically the "reduction" module in forecasting.
https://github.com/alan-turing-institute/sktime

We are currently refactoring that, so would it make sense to work together?

A possible model could be to have interface compatibility, and a "special module" for reduction (direct, recursive, etc)?

Would you like to meet and chat?

**Comment by fkiraly** [comment]
(you can drop me a line here to find a time if interested to set up the meet 😄 
https://join.slack.com/t/sktime-group/shared_invite/zt-1cghagwee-sqLJ~eHWGYgzWbqUX937ig )

**Comment by JoaquinAmatRodrigo** [comment]
Hi @fkiraly,
Sure, let's meet and talk. Is it fine if I text you to f.kiraly@ucl.ac.uk?

**Comment by BrandonKMLee** [comment]
This looks interesting @fkiraly what is it about, compared to https://github.com/winedarksea/AutoTS ?

**Comment by JoaquinAmatRodrigo** [comment]
Hi, 
It has been more than 60 days since the last activity on this GitHub issue. Since we have not received any updates or progress reports, we will be closing this issue.

If this issue is still relevant and requires attention, please feel free to reopen it and provide an update. We appreciate your contributions and would love to see this issue resolved if it is still relevant.

Thank you for your participation and cooperation!
