### ISSUE TITLE
Plot the curve for learning of an lgbm forecaster

### ISSUE THREAD

**Issue by DariusMargineanNicolae** [JoaquinAmatRodrigo/skforecast#224]
Hello! I am new to sk.forecast.ForecasterAutoReg. I tried to implement an LGBM model, and make the predictions on 4 steps ahead. I did manage to visualize the predictions, but I struggle how to plot the curve for the learning part to see how the model performs on the learning dataframe. Below is the code I have used. 

`forecaster = ForecasterAutoreg(
            regressor=LGBMRegressor(**lgbm_trial_params), lags=[1,2,3,4]
        )

cols = [col for col in df.columns if col not in ['date', "Qty"]]
exog = df[cols]

forecaster.fit(y=df["Qty"][:-4], exog=exog[:-4])
predictions = forecaster.predict(steps = 4,exog = exog[:-4])`

Qty represents the target variable I want to predict and my dataframe is structured on weekly data with month, week_num and last_month_average as features.

Here is a printscreen of the structure of my dataframe:

![image](https://user-images.githubusercontent.com/94625620/186508440-933fc818-9fd7-452b-9cfd-18e45399f9d0.png)

I did not manage to find something useful searching the internet so any help will be much apreciatted. Thanks!

**Comment by JoaquinAmatRodrigo** [comment]
Hi @DariusMargineanNicolae 
I am not sure if I undertood the issue. Do you mean you would like calculate predictions on the training data set?

**Comment by DariusMargineanNicolae** [comment]
> Hi @DariusMargineanNicolae 
> 
> I am not sure if I undertood the issue. Do you mean you would like calculate predictions on the training data set?

Hello @JoaquinAmatRodrigo . Thanks for your reply. Basically yes, I want to view the predictions on the training data set also and then plot them along with the actual data to see how the model behave during training.

**Comment by JoaquinAmatRodrigo** [comment]
The following steps should work:

1) Train the forecaster as you are doing.
2) Set arguments initial_train_size=None and refit=False to perform backtesting using the already trained forecaster.

Two observations:

-  It is important that, during the backtesting you use the same steps as in the training, other your backtesting would be too optimistc.
-  The first 4 observations are not predicted since they are needed to create the lags used as predictors.

You can find an example here: https://joaquinamatrodrigo.github.io/skforecast/0.4.3/notebooks/backtesting.html#predict-using-backtesting_forecaster

**Comment by DariusMargineanNicolae** [comment]
It worked. Thanks a lot for your time! I will close the issue now.
