### ISSUE TITLE
In `grid_search_forecaster` and `backtesting_forecaster`, does the algorithm use lagged real value or lagged predicted value?

### ISSUE THREAD

**Issue by kaionwong** [JoaquinAmatRodrigo/skforecast#228]
I have split my data into training, validation, and test set. However, while the documentation says in recursive multi-step forecasting, the lagged values came from predicted values ([link](https://joaquinamatrodrigo.github.io/skforecast/0.4.3/quick-start/introduction-forecasting.html)), and not from the actual values in the test set. I have some doubt from the results of my code:

```
    outer_start_date = '2017-01-07'
    outer_end_date = '2021-08-21'
    end_train = '2019-06-01'
    end_validation = '2020-07-01'

    selected_forecaster = 
    lags_grid = [1, 2, 10, 26, 52, 60, [1, 52]] 
    autoregressive_n_lag = 104 
    future_prediction_n_step = 8

    forecaster = ForecasterAutoreg(
        regressor=XGBRegressor(random_state=123),
        lags=autoregressive_n_lag  # This value will be replaced in the grid search
    )

    results_grid = grid_search_forecaster(
        forecaster=forecaster,
        y=df.loc[:end_validation, 'REPORTED_CASES'],
        exog=df.loc[:end_validation],
        param_grid=param_grid,
        lags_grid=lags_grid,
        steps=future_prediction_n_step,
        metric=curr_performance_metric,
        refit=refit_in_last_backtest,
        initial_train_size=len(df[:end_train]),
        fixed_train_size=fixed_train_size_in_last_backtest,
        return_best=True,
        verbose=False
    )

    metric, predictions = backtesting_forecaster(
        forecaster=forecaster,
        y=df.REPORTED_CASES,
        initial_train_size=len(df.REPORTED_CASES[:end_validation]),
        fixed_train_size=fixed_train_size_in_last_backtest,
        steps=future_prediction_n_step,
        metric='mean_absolute_error',
        refit=refit_in_last_backtest,
        interval=[5, 95],
        n_boot=500,
        in_sample_residuals=True,
        verbose=False
    )
```
![image](https://user-images.githubusercontent.com/61426243/187003318-d67d77a2-69a0-4ffb-ab00-41b0511e5582.png)

The model has no features other than the lags based on `lags_grid=[1, 2, 10, 26, 52, 60, [1, 52]] `. If the assumption is true that lag terms were computed from predicted values in the test set, I shouldn't be seeing this current result that the forecaster seemed to know and matched closely of the drop right before 2020. And we would expect the forecaster to predict a peak in mid/late 2020, which it didn't.

When I changed the lag grid to `lags_grid = [[26, 52]]`, it shows the following which confirms my theory. 

![image](https://user-images.githubusercontent.com/61426243/187004324-08fc198d-9362-4e38-8528-ffbe12c7c4b0.png)

Can someone please confirm how lags are chosen during backtesting in the test set? Is there any option I can use the predicted values' lags instead of actual values' lags for the forecasting of the test set values?

**Comment by JoaquinAmatRodrigo** [comment]
Hi @kaionwong,

The process of backtesting  mimic what would have happened if the forecaster would have been in production.  If the predicted values are used recursively as lags depends on how many  steps ahead you want to predict. For 1 step ahead prediction, only real values are used since they are available. For multi-step scenarios, previously predicted values need to be used as lags.

Let's assume you train an autoregressive forecaster with 4 lags and you are interested on predicting a 10 steps horizon. In each backtesting partition:

- There will be 10 prediction steps.
- The  first prediction will use the 4 real values as lags, the second will use 3 real values and 1 predicted. After the fourth prediction all lags will be predicted values.

Each partiton of backtesting starts using real values, not the predictions of previous partitions.

I hope this helps to understand how backtesting is programmed.

**Comment by kaionwong** [comment]
That makes sense, thank you @JoaquinAmatRodrigo
