### ISSUE TITLE
Support pandas 1.2.0 and  set_output(transform="pandas")

### ISSUE THREAD

**Issue by marcm-ml** [JoaquinAmatRodrigo/skforecast#335]
Hello,

is there any plans to bump the requirements for sklearn to 1.2.0 and test the new set_output api introduced in 1.2.0 [(see here)](https://scikit-learn.org/stable/auto_examples/miscellaneous/plot_set_output.html)?

**Comment by JoaquinAmatRodrigo** [comment]
Hi @marcm-ml,

Yes, we will try to be updated with the last sklearn releases.
How do you think the set_output api could improve the current functionalities of skforecast?

Best

**Comment by JavierEscobarOrtiz** [comment]
Hi,

It has been more than 60 days since the last activity on this GitHub issue. Since we have not received any updates or progress reports, we will be closing this issue.

If this issue is still relevant and requires attention, please feel free to reopen it and provide an update. We appreciate your contributions and would love to see this issue resolved if it is still relevant.

Thank you for your participation and cooperation!
