### ISSUE TITLE
DeprecationWarning: `np.int` is a deprecated with Numpy>=1.20

### ISSUE THREAD

**Issue by davidusb-geek** [JoaquinAmatRodrigo/skforecast#350]
First and foremost thank for this amazing module!

I have this annoying warning when using the `bayesian_search_forecaster` with  `skopt`:
```
DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  return np.round(X_orig).astype(np.int)
```

The dependencies for `skforecast` includes `numpy>=1.20`.  This a known issue and the problem is that `skopt` seems to be not longer maintained.

So is there a solution that you propose to solve this?
Downgrading `numpy` to < 1.20 solves this warning but then that version is not compatible with `skforecast` demanding `numpy>=1.20`.
What were your reasons to fix `numpy>=1.20`?

**Comment by JoaquinAmatRodrigo** [comment]
Hi @davidusb-geek ,
Thank you very much for using skforecast!

You are right, `skopt` is not compatible with `numpy` versions > 1.24. We initially set `numpy>=1.20` because it is the oldest version we tested but we may have been too conservative.

Currently, the only solution to hide this warning may be:

```
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning) 
```

Since it seems that `skopt` is no longer maintained, we have decided to stop using this engine within `bayesian_search_forecaster` in favor of  `optuna` .  From the user's perspective, nothing should change.

The new 0.8.0 release will be published at the end of this week.

I hope this help!

**Comment by JavierEscobarOrtiz** [comment]
Thank you for your comments @davidusb-geek 

Check the user guide for `bayesian_search_forecaster` with `optuna` engine:

https://joaquinamatrodrigo.github.io/skforecast/latest/user_guides/hyperparameter-tuning-and-lags-selection.html#optuna

**Comment by davidusb-geek** [comment]
Thank you for your prompt replies!

My reason to stick to skopt was that it is much more ligth-weight. Which is very important for containerized solutions using Docker. But I totally understand the need to switch to a maintained solution.

Thanks for the tips to update to the optuna implementation.

**Comment by JoaquinAmatRodrigo** [comment]
Let us know if you find any problems using `optuna`  engine!

**Comment by davidusb-geek** [comment]
Thanks, will do.
