### ISSUE TITLE
Confusing documentation regarding Independent multi-time series forecasting and exogenous features

### ISSUE THREAD

**Issue by valentin-fngr** [JoaquinAmatRodrigo/skforecast#531]
Hi, 

in your code example : Independent multi-time series forecasting. 
You are providing a very good tutorial on how to learn from independent multi time series, BUT, you do not provide any indication on how to provide exogenous features ? 

There is drawing which confuses me a lot, as I do not know I am supposed to process my dataframe that way or you are just showing what is happening behind the hood : 

![image](https://github.com/JoaquinAmatRodrigo/skforecast/assets/42917280/cbc3a8e3-9f33-459e-8450-59b55ad57d3c)

I have the following columns : 

id : the id of my time series 
X1 - X800 : a list of 800 features 
y : my target 

What dataframe format is **backtesting_forecaster_multiseries** expecting ? 
 
The given dataset used in the example and the drawing above do not align. 

Thank you very much

**Comment by valentin-fngr** [comment]
After reading the source code, I figured that the drawing is representing what is happening under the hood. 
Nonetheless, I believe this is confusing and does not help on how to prepare the data in the case of multi_series + exogenous features. 

I still do not know how to prepare my data in that case.

**Comment by JoaquinAmatRodrigo** [comment]
Hi @valentin-fngr,
Thanks for using skforecast.
You are right, the graph represents the transformation applied internally by the forecaster.
The current implementation does not allow to use a different exogenous variable for each time series, they are considered as global for all of them.

We will try to improve the documentation in the next release for better clarity.

**Comment by JavierEscobarOrtiz** [comment]
Hello @valentin-fngr

Thanks for opening the issue. If I understand you correctly, your problem is that you want to add a different exogenous variable per series. Could you give us some information about your use case? We have this feature in the backlog, but the only use case that comes to my mind that needs this is for example modeling a time series by countries and you need a different vacation indicator for each of them.

As for the documentation, yes, you are right, this is what happens under the hood. Please see the updated user guide at the following link, where I have added a new section on exogenous variables:

https://github.com/JoaquinAmatRodrigo/skforecast/blob/feature_update_tests/docs/user_guides/independent-multi-time-series-forecasting.ipynb

It is important to know that the dataframe that `ForecasterAutoregMultiSeries` expects looks like this:

![imagen](https://github.com/JoaquinAmatRodrigo/skforecast/assets/95030312/14958614-f080-4e93-8f41-e1256ac1180d)

One column for each target variable (item_1, item_2 and item_3) and additionals with the exogenous variables.

Please, let us know your thoughts on this 😄

**Comment by valentin-fngr** [comment]
Hi @JavierEscobarOrtiz, 

Thanks for your reply. 
Here is my use case : 

I have 10 different stocks (my time series). All of them have the same 100 features X1 to X100 but with different values. 
for example : 

<img width="232" alt="image" src="https://github.com/JoaquinAmatRodrigo/skforecast/assets/42917280/641860e5-07d9-473e-8289-c08b48d25e15">

Here, HUB is the time serie id. imagine you have different values for hub.

I thought about implementing the feature and submitting a pull request, I started, but time was ticking and I could not propose a clean pull request with all associated tests. 

Regarding your modification, I think it is much better and clears any confusion. I would really suggest to build that feature as a lot of people might benefit from it. 

Valentin

**Comment by valentin-fngr** [comment]
Do you have any workaround regarding my specific problem ? 
I would like to keep using your library for its simplicity.

**Comment by JoaquinAmatRodrigo** [comment]
Hi @valentin-fngr,
Unfortunately, we do not currently have a solution for incorporating different exogenous variables for each series in the multi-series forecasting models.  However, this feature is currently on our radar and is part of our backlog for upcoming feature releases. 

We are always open to new ideas. If you have any suggestions, we would be happy to discuss them with you.
