### ISSUE TITLE
Feature Importance for Independent multi-series forecasting

### ISSUE THREAD

**Issue by abseejp** [JoaquinAmatRodrigo/skforecast#570]
Hey I have a quick question about using SkForecast. If I'm using the independent time series approach, I see it's possible to build just one model that can forecast multiple series but is there a way to see the feature importance of each model built underneath? Tried forecaster.get_feature_importances but that's not working. If I have three timeseries, I want to be able to see the exogenous feature importance for each of the three models. 

Let me know if there's anything I'm doing wrong.

**Comment by JoaquinAmatRodrigo** [comment]
Hi @abseejp,
Thanks for using skforecast.
In independent multi-series forecasting (`ForecasterAutoregMultiSeries`) a single model is trained for all time series, therefore, there are not several underlying models. `forecaster.get_feature_importances` should return the feature importance for the model. Are you getting any errors?

**Comment by abseejp** [comment]
Thanks for the comment. I just tried it again now, and it's working, but I have another question following your response. If you're fundamentally building a single model, do you assume that an exogenous feature will have a fixed relationship (i.e., same importance value) with all the timeseries? For instance, if the importance value for ` lag 1` is `0.493775` and I have three timeseries, does that means the importance is still `0.493775` for` series 1,2, and 3`?

Please help me understand what's happening internally. I would have assumed that since I have three timeseries, then I should get three different feature importance dataframe (one for each series and the importance values of a feature should be different for each series).

**Comment by JoaquinAmatRodrigo** [comment]
I see where the confusion might be coming from. When you're working with a single model for multiple time series, the importance values are calculated in relation to the entire dataset (all series together), not on a per-time series basis. This is because the underlying assumption is that all series being modeled together share a common underlying pattern.

In your example, if the importance value for lag 1 is 0.493775, it means the importance of lag 1 for the overall group of series included in the model. This importance is derived from the training process and reflects how influential that feature is on the predictions across the entire dataset. This importance value is not specific to any one time series.

If you want to get feature importance specific to each individual time series, you would typically have to train separate models for each series. Each of these models would then provide a different set of importance values, tailored to the particular characteristics of the individual time series.

The feature importance for each "item" is a measure of how each individual series influences the response variable according to the trained model.

A diagram illustrating how the training matrix is created may help to understand the feature importance output.

![image](https://github.com/JoaquinAmatRodrigo/skforecast/assets/13439059/320448f5-f802-4b89-880c-9874adcea64e)

**Comment by abseejp** [comment]
Thanks for your response. Really helpful.
