### ISSUE TITLE
support more than 2 percentiles to be passed for `predict_interval`

### ISSUE THREAD

**Issue by yarnabrina** [JoaquinAmatRodrigo/skforecast#572]
I'm working on creating a back-adapter for `skforecast` models in `sktime`, starting with `ForecasterAutoreg`. The goal is to provide an option to use `skforecast` as an backend alternative to the already existing `make_reduction`. During this, I notice that currently it enforces `interval` to be a list of values in `[0, 100)`, even though it's not necessary that they sum up to 100.

While as a single confidence interval it makes sense, enforcing length does not seem to be a necessity as you are calculating the quantiles from bootstrapping predictions.

https://github.com/JoaquinAmatRodrigo/skforecast/blob/db04f762d878c096b87b97de1a20f35025bbc437/skforecast/ForecasterAutoreg/ForecasterAutoreg.py#L990

If you remove the fixed length requirement, it will be easier to integrate in `sktime` for `predict_quantiles` methods, otherwise it'd need an otherwise unnecessary for loop or calling `predict_bootstrapping` directly and calculating `quantiles` in the back adapter itself. Can it be considered as a feature request?

If you have any other suggestion to address this without this feature request, that will be much appreciated as well.

**Comment by JoaquinAmatRodrigo** [comment]
Hi @yarnabrina,
Thanks for using skforecast.

What you suggest makes perfect sense. Since the heavy computation relies on the bootstrapping process, the user may benefit from calculating multiple quantiles with a single function call.  

@JavierEscobarOrtiz What are your thoughts? We will need to check if this change affects the other parts of the API to estimate the effort required. But if all goes well, this may be a feature to include in the next release.

**Comment by JavierEscobarOrtiz** [comment]
Hello @yarnabrina,

Thanks for opening the issue!

Your suggestion sounds very interesting. It is true that sometimes you are not interested in the lower and upper bounds of an interval, but you are looking for some specific quantiles.

Regarding our method `predict_interval`, we have discussed and decided to leave it as it is, since the purpose of this method, as its name suggests, is just to get an interval (lower and upper bound). 

So, two solutions come to my mind at this point:

1. You can imitate our `predict_interval` code and modify the line you pointed out. As I see it, you will not need a for loop because all the calculations are done in `predict_bootstraping` and you just have to call the desired quantiles with the numpy quantile method.

2. Since I may be missing some behavior in your code and the feature you suggest is very interesting, we will create a method called `predict_quantiles` with the behavior you mention for the next version. 😄 This will also help us to avoid making a lot of changes in the code of functions like `backtesting_forecaster` (since they use the `predict_interval` method internally).

Hope this comment fits your needs.

**Comment by yarnabrina** [comment]
Hi @JoaquinAmatRodrigo, @JavierEscobarOrtiz, thanks for your comments. Yes, I can definitely start with quantile calculation in `sktime`.

I just created https://github.com/sktime/sktime/pull/5447 with solution 1 above, and will switch to 2 when available. It'll be great if you can take a look and give some feedbacks on other parts and the feasibility of the TODO comments mentioned in the PR.

**Comment by yarnabrina** [comment]
Closed by #577 based on my understanding.

**Comment by JavierEscobarOrtiz** [comment]
@yarnabrina correct, 

There will be a change where the output columns of `predict_quantile` will be named as `q_0.0.5, q_0.50` ...

It will come in a future PR.
