### ISSUE TITLE
"ForecasterAutoreg" Object has no attribute "differetiation" 

### ISSUE THREAD

**Issue by davidusb-geek** [JoaquinAmatRodrigo/skforecast#573]
Everything was working fine but just updated to 0.10.1 and now got this error 🔢 

![image](https://github.com/JoaquinAmatRodrigo/skforecast/assets/32926550/630dfad9-37d5-4299-a46f-d7b1cd4c9b60)

That update was not backward compatible with that breaking change?

**Comment by JavierEscobarOrtiz** [comment]
Hello @davidusb-geek, this should not be happening 😓 

Can you please share a reproducible example of the code?

Thank you!

**Comment by JavierEscobarOrtiz** [comment]
Hello again @davidusb-geek, I think the cause of your problem is because you are using a forecaster created in a lower version of skforecast ( < 0.10.x). Can be?

We are going to evaluate it but a quick fix will be re-create your forecaster object before passing it to the bayesian search function

Hope it helps!

**Comment by davidusb-geek** [comment]
Solved retraining the model.
