### ISSUE TITLE
Disable progress bar

### ISSUE THREAD

**Issue by ZhikangLai** [JoaquinAmatRodrigo/skforecast#661]
Hello there. skforecast is excellent package. But I think some functions need to be improved. For instance, When I call the model, and I will out lots of training message(train bar). Not everyone needs this information. So I think the creator of this toolbox can add this feature which can let user choose for themselves whether to ignore information about the training process.

![1712800773636](https://github.com/JoaquinAmatRodrigo/skforecast/assets/110596898/2226d6c9-19fe-4078-97e9-a9b0e0b0e4b4)

**Comment by JavierEscobarOrtiz** [comment]
Hello @ZhikangLai 

You can suppress the progress bar in all the `model_selection` functions with the argument `show_progress = False`.

Regarding the print, it is caused by `return_best = True`. Skforecast doesn't have the option to suppress this print if you want skforecast to refit the model after the hyperparameter search.

Hope it helps
