### ISSUE TITLE
Creating lag and rolling window (mean, skew, std...) features?!

### ISSUE THREAD

**Issue by nezirspanca** [JoaquinAmatRodrigo/skforecast#797]
Hello there,

Thank you for your work and this great library.

My question would be, what is the best method to create features like rolling window or lagged variables for exogenous variables in e.g. ForecasterAutoregDirect without causing data leakage?

 Lets say I have this data:
index     |    y  |   exog1 |   exog2         
1   |     5     |    120    |      58
2   |    10    |    160    |      70
3   |    15    |    130    |       80
4   |    20    |    140    |      60

I would also be interested in target variable, for example rolling window, or mean max and mean min...?

I am asking this question because I am creating a model for forecasting in the next 36 hours with a 12 hour gap. And my model created with ForecasterAutoregDirect, as can be seen in the photo, makes good forecasts, but still it is not capturing the peaks. And now I was thinking of creating some extra features in the target variable and exog variables that might contain valuable information for the model. But I'm having trouble doing this in ForecasterAutoregDirect (because that's giving the best results).

![Forecast1](https://github.com/user-attachments/assets/4996736d-3b35-4b32-b5f9-5da1fed07cf7)

**Comment by JavierEscobarOrtiz** [comment]
Hello @nezirspanca,

Thanks for opening the issue. Right now the `ForecasterAutoregDirect` doesn't allow to include window features from the target variable. For this you should use the `ForecasterAutoregCustom`, this forecaster follows a recursive strategy instead of the direct one:

https://skforecast.org/latest/user_guides/window-features-and-custom-features

On the other hand, if you want to create window features as exogenous variables, remember that you will need to know their future values to predict your target variable. I recommend to create a `pd.DatetimeIndex' in your exog DataFrame and use the [pandas rolling method](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html)

Hope it helps!

Javi

**Comment by JavierEscobarOrtiz** [comment]
It all dependes how you create your rolling exogenous variables.

https://cienciadedatos.net/documentos/py29-forecasting-electricity-power-demand-python.html

Check the "exogenous variables" section of this notebook. The rolling is set with `closed = 'left'`, so the last point in the window is excluded from calculations. For example:

```python
temp_features['temp_roll_mean_7_day'] = temp_features['Temperature'].rolling(24*7, closed='left').mean()
```

This means that the point $t$ doesn't contain any information from the point $t + 1$, thus avoiding data leakage. With this method, the `backtesting_freocaster' configuration you mention can be use.

**Comment by nezirspanca** [comment]
Thanks @JavierEscobarOrtiz for the suggestion, I will try it with these features, maybe I can improve my prediction even more.

I had one last question, do you think it could also work to create lag features for exogenous variables, by writing a few lines of code in this part where I will also create rolling variables? Because I have usually created the lag features after splitting into train and test data, but here I am not sure.

**Comment by JavierEscobarOrtiz** [comment]
Yes, it could work. I recommend using `get_features_importances` to know if the regressor gives a high weight to these variables.

**Comment by nezirspanca** [comment]
Thank you for your help and all suggestions. Im closing the issue 😊.
